TodoApp/TodoApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
]

TodoApp/tasks/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy
from . views import (TaskListView,
                     TaskDetailView,
                     TaskCreateView,
                     TaskDeleteView,
                     CreateUserView,
                     LoginView)

app_name = 'tasks'
urlpatterns = [
    path("", TaskListView.as_view(), name="home"),
    path("detail/<int:id>/", TaskDetailView.as_view(), name="detail"),
    path("delete/", TaskDeleteView.as_view(), name="delete"),
    path("save/", TaskCreateView.as_view(), name="create"),
    path("save/<int:id>/", TaskCreateView.as_view(), name="create-param"),
    path("register/", CreateUserView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page=reverse_lazy('tasks:register')), name="logout"),
]

TodoApp/tasks/models.py
from django.db import models
from django.conf import settings


class Task (models.Model):
    title = models.CharField(max_length=50)
    detail = models.TextField()
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
    due_date = models.DateField(auto_now=False, auto_now_add=False)
    isCompleted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.title} {self.created_at}"

TodoApp/tasks/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from . models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

TodoApp/tasks/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.forms.models import model_to_dict
from django.http import JsonResponse
from . models import Task
from . forms import TaskForm, CustomUserCreationForm
from django.contrib.auth import authenticate, login
import json


class TaskListView(LoginRequiredMixin, View):
    model = Task
    template_name = 'tasks/index.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            query = request.GET.get('status', '')
            if query and (query.lower() == 'pending' or query.lower() == 'completed'):
                filter = False if query.lower() == 'pending' else query.lower() == 'completed'
                querysets = self.model.objects.filter(
                    owner=request.user.id, isCompleted=filter).order_by('-created_at').values()
            else:
                querysets = self.model.objects.filter(
                    owner=request.user.id).order_by('-created_at').values()
            context = {'tasks': querysets, 'user': request.user,
                       'authenticated': request.user.is_authenticated}
            return render(request, self.template_name, context)


class TaskDetailView(LoginRequiredMixin, View):
    model = Task

    def get(self, request, id):
        if request.user.is_authenticated:
            obj = self.model.objects.get(id=id)
            serialized_data = []
            data = model_to_dict(
                obj, fields=[field.name for field in obj._meta.fields])
            data['created_at'] = str(obj.created_at)
            serialized_data.append(data)
            return JsonResponse(serialized_data, safe=False)
        return JsonResponse({'error': 'Something went wrong'}, status=400)


class TaskCreateView(LoginRequiredMixin, View):
    model = Task
    template_name = 'tasks/index.html'

    def post(self, request, id=None):
        if request.user.is_authenticated:
            form = TaskForm(request.POST)
            if id:
                obj = self.model.objects.get(id=id)
                form = TaskForm(request.POST, instance=obj)
            if form.is_valid():
                cleaned_data = form.cleaned_data
                cleaned_data['owner'] = request.user.id
                form.save()
                return JsonResponse('successful', safe=False)
            else:
                print('this error')
                errors = form.errors
                return JsonResponse({'error': 'Invalid fields', 'details': errors}, status=400)
        return JsonResponse({'error': 'Something went wrong'}, status=400)


class TaskDeleteView(LoginRequiredMixin, View):
    model = Task

    def post(self, request):
        if request.user.is_authenticated:
            try:
                data = json.loads(list(request.POST)[0])
                obj = self.model.objects.get(**data)
                obj.delete()
                return JsonResponse('success', safe=False)
            except:
                return JsonResponse({'error': 'Something went wrong'}, status=400)
        return JsonResponse({'error': 'Something went wrong'}, status=400)


class CreateUserView(View):
    form = CustomUserCreationForm
    template = 'registration/register.html'

    def get(self, request):
        return render(request, self.template, {'form': self.form()})

    def post(self, request):
        form = self.form(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('tasks:home')
        else:
            error_messages = {}
            for field, errors in form.errors.items():
                for error in errors:
                    error_messages[field] = error
                    print(error)
            context = {
                'form': CustomUserCreationForm(),
                'messages': error_messages
            }
            return render(request, self.template, context)


class LoginView(View):
    template = 'registration/register.html'

    def get(self, request):
        return render(request, self.template, {})

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('tasks:home')
        else:
            context = {
                'message': 'Invalid username or password'
            }
            return render(request, self.template, context)

TodoApp/tasks/templates/tasks/display.html
<form id="myForm" method="post">
  {% csrf_token %}
  <div class="form__title-div">
    <input type="hidden" name="owner" value="{{request.user.id}}" />
    <label for="title">Title:</label>
    <input type="text" name="title" id="title" placeholder="title" />
  </div>
  <div class="form__detail-div">
    <textarea
      name="detail"
      id="detail"
      cols="40"
      rows="10"
      placeholder="tell us more"
    ></textarea>
  </div>
  <div class="form__date-div">
    <label for="due_date">Due_date:</label>
    <input type="date" name="due_date" id="due_date" />
  </div>
  <div>
    <label for="isCompleted">Completed:</label>
    <input type="checkbox" name="isCompleted" id="isCompleted" />
  </div>
  <div class="error__div">
    <p id="errorMessage"></p>
  </div>
  <div class="form__button-div">
    <button type="submit" id="submitBtn" class="create_btn" data-type="create">
      Add
    </button>
  </div>
</form>

TodoApp/tasks/templates/tasks/index.html
{% extends "base.html" %} {% load static%} {% block css%}
<link rel="stylesheet" type="text/css" href="{% static 'tasks/task.css' %}" />
<script defer src="{% static 'tasks/js/index.js' %}"></script>
{% endblock %} {% block content %}
<section id="taskSection" class="task__section">
  <div class="task__list">
    <nav class="task__list-nav">
      <ul>
        <li
          class="{% if request.path == '/' and not request.GET.status %}nav-active{% endif %}"
        >
          <a href=".">All</a>
        </li>
        <li
          class="{% if request.GET.status|lower == 'pending' %}nav-active{% endif %}"
        >
          <a href="?status=pending">Pending</a>
        </li>
        <li
          class="{% if request.GET.status|lower == 'completed'%}nav-active{% endif %}"
        >
          <a href="?status=Completed">Completed</a>
        </li>
      </ul>
    </nav>
    <div class="tasks__list">
      <div id="addButton" class="add-icon">
        <i class="fa fa-plus"></i>
      </div>
      {% if tasks|length > 0 %} {% for task in tasks %}
      <div class="task" data-id="{{task.id}}">
        <div class="task__details">
          <h3>{{task.title}}</h3>
          <p>{{task.detail|truncatewords:7}}</p>
          <p>{{task.created_at}}</p>
        </div>
        <div class="task__icons">
          {% if task.isCompleted %}
          <i class="fa fa-check task-done"></i>
          {% else %}
          <i class="fa fa-times task-undone"></i>
          {% endif %}
          <button type="button" class="deleteButton">
            <i class="fa fa-trash-can"></i>
          </button>
        </div>
      </div>
      {% endfor %}
      {% else %}
        <div class="no-task">
          <h1>Create a task</h1>
        </div>
      {% endif %}
    </div>
  </div>
  <div class="task__edit">
    <h2>Add Task</h2>
    {% include "tasks/display.html" with tasks=tasks request=request %}
  </div>
</section>
{% endblock %}

TodoApp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static '@fortawesome/fontawesome-free/css/all.min.css' %}"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    {% block css %} {% endblock%}
    <title>Document</title>
  </head>

  <body>
    <header id="header" class="header">
      <nav class="navbar">
        <h2>Todo <span>App</span></h2>
        <div class="nav-links">
          <h3>Welcome {{request.user}}</h3> 
          <h4>
            <a href="{% url 'tasks:logout' %}">logout</a>
          </h4>
        </div>
      </nav>
    </header>
    <main>{% block content %} {% endblock %}</main>
  </body>
</html>